[Android] Fix for Talkback reporting incorrect number of list items (#4090)
xamarin/Xamarin.Forms pull request #10151
Opened 2020-03-31 15:50 UTC by nicolasdeory

### Description of Change ###

The native ListView control in Android had two phantom items (header and footer). Even if they were invisible, they still counted toward the children count. Therefore, a list with 2 items would get narrated as "a list of 4 items".

### Issues Resolved ### 

- fixes #4090

### API Changes ###

None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Run Issue4090 in Control Gallery.
When clicking 'Browse' or 'About', Talkback should report that the element is in a list of 2 items.

### PR Checklist ###
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-03-31 15:50 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=10151) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=10151) before we can accept your contribution.<br/><br/>:x: nicolasdeory [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=10151)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=10151) it.</sub>

2020-04-02 23:20 UTC, samhouts commented
@nicolasdeory It looks like too many commits are here. Can you please rebase on 4.6.0? Thanks!

2020-04-03 09:00 UTC, nicolasdeory commented
@samhouts I've done the rebase and the extra commits are gone, but the PR isn't updating for me, it still displays 25 commits. Should I create a new PR?

2020-04-03 20:42 UTC, nicolasdeory commented
@samhouts It should be fixed now. Sorry for the inconvenience!

2021-01-18 19:32 UTC, PureWeen commented
/azp run

2021-01-20 15:34 UTC, PureWeen requested changes
I know it's been awhile so if you don't have time to check this one out @nicolasdeory we can take it over but it looks like this PR is causing a number of tests to fail

![image](https://user-images.githubusercontent.com/5375137/105197915-bc2c1580-5b02-11eb-9cc8-02d5f3f7f4f5.png)

2021-01-20 15:47 UTC, nicolasdeory commented
Unfortunately I can't take a thorough look at it at the moment. I'm puzzled as to why those tests are failing, especially because the code change is minimal.

2022-01-11 17:30 UTC, mounikakola commented
Any update on this?

2022-01-14 13:29 UTC, jfversluis commented
@mounikakola can you confirm this is still an issue with the latest Xamarin.Forms stable? Even when you have the feature flag enabled as described in https://github.com/xamarin/Xamarin.Forms/issues/1529#issuecomment-962200361

If yes, and you would still like to see this fixed, would you be willing and able to take this on yourself? I see that this functionality has been moved over for .NET MAUI where it will definitely be fixed, but if you would like to see it for Forms as well, the best chance of getting it in would be if you could help us. Thanks!

Closing this one for now as we're focussing this for .NET MAUI for now and/or might be already fixed

2022-01-14 13:29 UTC, closed without merging