[Android/iOS] Fix programmatically open right SwipeItems
xamarin/Xamarin.Forms pull request #10575
Opened 2020-05-05 11:16 UTC by jsuarezruiz

### Description of Change ###

Changes:
- Fix programmatically open right SwipeItems.
- Added animated parameter to open and close the SwipeView.

### Issues Resolved ### 

- fixes #10563

### API Changes ###
 
Added **Animated** parameter to `OpenSwipeEventArgs` and `CloseSwipeEventArgs`.

### Platforms Affected ### 

- iOS
- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

![fix10563](https://user-images.githubusercontent.com/6755973/81060191-40d1f780-8ed2-11ea-8edd-b6fa9bfab935.gif)
![animated-openclose-swipeview](https://user-images.githubusercontent.com/6755973/81060194-42032480-8ed2-11ea-9b85-f4feda3600d2.gif)

### Testing Procedure ###

### PR Checklist ###

- [x] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-06-29 13:44 UTC, jsuarezruiz commented on Xamarin.Forms.Core/SwipeEventArgs.cs
> +	public class CloseSwipeEventArgs : EventArgs
Renamed.

2020-06-29 14:05 UTC, jsuarezruiz commented
@PureWeen Added UITests.

2020-06-30 14:09 UTC, hartez commented on Xamarin.Forms.Core/SwipeEventArgs.cs
> +	public class CloseSwipeEventArgs : EventArgs
Now that I look at this again, we should match the event names with the event arguments names as closely as we can. So now I think it should be `CloseRequestedEventArgs` and `OpenRequestedEventArgs`.

2020-07-04 01:23 UTC, PureWeen commented
works great

Should the open behavior be blocked if it's already open in a different direction?

If I click Open Right and then click Open Left should it open Left now? Is there any reason to block that request if it's already open?

2020-07-23 15:11 UTC, hartez commented
> Should the open behavior be blocked if it's already open in a different direction?
> 
> If I call Open Right and then call Open Left should it open Left now? Is there any reason to block that request if it's already open a different direction?

I can't think of any reason we should block it, as long as we can gracefully transition from one open state to the other.

2020-09-14 14:15 UTC, jsuarezruiz commented
@hartez Renamed the SwipeView Open/Close EventArgs to `CloseRequestedEventArgs` and `OpenRequestedEventArgs`.

2020-09-14 15:36 UTC, jsuarezruiz commented
Applied changes to no block the open behavior if it's already open in a different direction:
![fix10563](https://user-images.githubusercontent.com/6755973/93106540-b0da6080-f6b0-11ea-8e1b-209b191e5cca.gif)

2020-11-10 22:35 UTC, PureWeen commented
/azp run

2020-11-20 14:37 UTC, PureWeen requested changes
UI Tests are failing

2020-12-14 17:58 UTC, rmarinho commented
@jsuarezruiz  tests are failing .. can you review please?

2020-12-15 11:17 UTC, jsuarezruiz commented
@rmarinho All the tests are passing now.

2020-12-15 17:25 UTC, hartez approved these changes

2020-12-17 12:58 UTC, rmarinho commented
@jsuarezruiz  seems its failing on iOS still..

2020-12-17 17:44 UTC, jsuarezruiz commented
<img width="367" alt="Captura de pantalla 2020-12-17 a las 18 42 55" src="https://user-images.githubusercontent.com/6755973/102523431-d1db9480-4097-11eb-8c97-e932f53cc9b7.png">

2020-12-18 11:04 UTC, rmarinho approved these changes

2020-12-18 11:05 UTC, merged