[Android] Changes in the logic to detect Device.Idiom
xamarin/Xamarin.Forms pull request #11206
Opened 2020-06-25 15:29 UTC by jsuarezruiz

### Description of Change ###

Changed checking the `UiMode` enum using HasFlag  to use  ==. Based on this changes https://github.com/xamarin/Essentials/commit/b937b1292840d8267969d6fe6f34a312aa6f9a36 from Xamarin Essentials.

### Issues Resolved ### 

- fixes #11166
- fixes #11177

### API Changes ###

 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-06-26 11:01 UTC, jsuarezruiz commented
Retarget to 4.5.0.

2020-08-18 12:30 UTC, jsuarezruiz commented
@PureWeen Yes, are failing the tests Issue2948 and Issue2951 although Device.Idiom is not used in these cases. Will take a look.

2020-09-04 11:04 UTC, PawKanarek commented
Maybe test didn't succeed, because of you need to accept some new agreements? 
@samhouts wrote: 

> For example, I just pinged a contributor yesterday about a test that I thought was legitimately failing, only to realize that it was actually failing because Chrome was asking us to accept the new terms of service. 🤦

2020-09-10 12:09 UTC, rmarinho commented
Going to rebase and run tests again .

Tests that were failoing were 2951 and 2948

2020-09-14 17:40 UTC, samhouts commented
Same tests are failing. @jsuarezruiz Can you investigate, please? Thanks!

2020-09-15 09:41 UTC, PawKanarek commented
Maybe i could potentially help with fix, but i have problems with identifying failing test, as im not familiar with azure pipeline... 
[Here](https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=2267&environmentId=94248&_a=release-environment-logs) i can see Message:

> "2020-09-10T15:18:47.5457580Z ##[error]There are one or more test failures detected in result files. Detailed summary of published test results can be viewed in the Tests tab."

But the Tests tab is empty :( 
![image](https://user-images.githubusercontent.com/15096514/93194154-0dd52580-f748-11ea-956f-1e726fae318f.png)

2020-09-16 09:00 UTC, jsuarezruiz commented
Updated the changes passing the failing UITests locally.
<img width="766" alt="Captura de pantalla 2020-09-16 a las 10 57 21" src="https://user-images.githubusercontent.com/6755973/93315708-a54f7c80-f80b-11ea-9b58-afc93b99c3f7.png">
Waiting for the Build results!

2020-11-04 21:49 UTC, PureWeen requested changes
I'm testing with the following code

```C#
			SetMainPage(new ContentPage()
			{
				Content = new StackLayout()
				{
					Children =
					{
						new Label()
						{
							Text = Device.Idiom.ToString()
						}
					}
				}
			});
```

And it's giving me back Unsupported. I'm testing on an API 23 emulator

if I roll back the changes here for Forms.cs then it gives me "Phone"

2020-11-06 15:19 UTC, jsuarezruiz commented
@PureWeen Updated fixing that issue. Could you try/review it again please?

2020-11-10 13:39 UTC, Redth approved these changes

2020-11-10 15:19 UTC, rmarinho approved these changes
Ok tested with @PureWeen  example, can get Phone and Tablet ok , in api 23/ api 29 , api 30

2020-11-10 15:19 UTC, merged