CSharpForMarkup Part 2
xamarin/Xamarin.Forms pull request #11428
Opened 2020-07-14 14:08 UTC by VincentH-Net

### Description of Change ###

> Note: this is a draft PR. All functionality for the July 15 cutoff is in place, but I still need to add some more unit tests to get 100% code coverage on the new functionality. My goal is to add these and make the PR final in time for the cutoff.

Add C# Markup helpers:

- For `MultiBind` and `MultiConverter`
- For `BindableLayout`
- For `RelativeLayout`
- For `DynamicResource`
- `Stars(double)` overload for defining rows and columns in Grids

Improvements:
- `Font` helper now has `family` as first parameter
- Padding helpers now work on all `IPaddingElement` view types

### Issues Resolved ### 
Fix for unreported issue uncovered by C# Markup unit tests:
`BindableLayout.SetEmptyViewTemplate` sets `EmptyView` instead of `EmptyViewTemplate`

### API Changes ###

 
None

### Platforms Affected ### 
- Core (all platforms)

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 
Not applicable

### Testing Procedure ###
Fully automated; all added and changed functionality is 100% covered with the included unit tests.

The new functionality was propotyped for usability in:
- [[Spec] C# Markup for MVU and MVVM](https://github.com/dotnet/maui/issues/119)
- GitTrends PR 
- [C# Markup versus Mobile Blazor Bindings in .NET MAUI](https://vincenth.net/blog/2020/07/11/c-markup-versus-mobile-blazor-bindings-in-net-maui)

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-08-19 17:19 UTC, samhouts commented
Hi @VincentH-Net! 

Thank you for continuing to improve this awesome feature! We want to keep the momentum going on building UI with C# code, and this is amazing work. 

We've been discussing this internally, and we think that this should move to the Xamarin Community Toolkit. We'd love to see continued innovation in this area, and the toolkit is the perfect place for that during this transition period between Xamarin.Forms and .NET MAUI.

Please join us on [Discord](https://aka.ms/dotnet-discord), if you haven't already, and we can discuss this further if you like!

Thanks again!

2020-10-30 09:21 UTC, VincentH-Net commented on Xamarin.Forms.Core/BindableLayout.cs
> +			b.SetValue(EmptyViewTemplateProperty, value);
Fix for `BindableLayout.SetEmptyViewTemplate` sets `EmptyView` instead of `EmptyViewTemplate`

2020-12-02 10:38 UTC, jsuarezruiz requested changes
@VincentH-Net  We have C# Markup extensions in the Xamarin Community Toolkit now. Some of this PR chcanges is pending in the Toolkit or can we close it?

2020-12-02 15:52 UTC, VincentH-Net commented
@jsuarezruiz  it can be closed, see the note in the pr description above:

> The features in this PR will not be included in Xamarin Forms. Instead they have been included in the Xamarin Community Toolkit C# Markup release. Go check it out!

2020-12-03 12:13 UTC, closed without merging