Update RefreshViewRenderer.cs
xamarin/Xamarin.Forms pull request #11532
Opened 2020-07-24 04:13 UTC by Jouna77

### Description of Change ###

Check if Element or control is null before attemping to change their status

### Issues Resolved ### 
Null reference exception on UpdateIsRefreshing when the window is resized

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###
None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-08-19 23:09 UTC, pictos commented
Hey @Jouna77, I'm helping the Team with code reviews. The change in the `yml` was intentional? If yes why?

2020-08-20 13:27 UTC, rmarinho requested changes
Shouldn't change the yml fiel like @pictos said.

2020-08-20 13:29 UTC, rmarinho approved these changes

2020-09-18 21:20 UTC, samhouts approved these changes

2020-10-29 12:30 UTC, merged