Correction of CollectionView to work properly with selected item colo…
xamarin/Xamarin.Forms pull request #11604
Opened 2020-07-30 09:25 UTC by ronymesquita

### Description of Change ###

The key idea is to resolve the problem that of `CollectionView` with selected item color of Android and iOS.

### Issues Resolved ### 

- fixes #7790
- fixes #9590

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS
- Android

### Behavioral/Visual Changes ###

The platform will check if exists a `Visual State` with `Selected` and not use the default color. In this manner, the background color the `Visual State` will not be overridden by Android or iOS.
The default behavior still works.

### Before/After Screenshots ### 

#### After (Android)
![android](https://user-images.githubusercontent.com/41541500/88905863-29827c00-d22d-11ea-9522-0e4bf0405053.gif)

#### After (iOS)
![ios](https://user-images.githubusercontent.com/41541500/88905900-343d1100-d22d-11ea-9d93-4ceb66e0f131.gif)

### Testing Procedure ###
The test was manual.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-07-30 09:25 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11604) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11604) before we can accept your contribution.<br/><br/>:x: ronymesquita [sign now](https://cla.dotnetfoundation.org/xamarin/Xamarin.Forms?pullRequest=11604)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/xamarin/Xamarin.Forms?pullRequest=11604) it.</sub>

2020-07-30 09:45 UTC, ronymesquita commented
The code no check to see if that are more than one `Visual State` with `Selected` state on the page.

2020-07-30 09:51 UTC, ronymesquita commented
The [SingleBoundSelection.xaml](https://github.com/xamarin/Xamarin.Forms/pull/11604/files#diff-92bb0a853f14e2626dd85a736dca9a06) file has been changed for testing purposes only.

2020-08-05 10:22 UTC, EmilAlipiev commented
we need this asap. workaround with visualstates doesnt work in every case.

2020-10-23 00:00 UTC, ronymesquita commented
Hello.

This pull request will be merged?

2020-10-27 06:21 UTC, developer9969 commented
Hi there is this going to be merged into 5?

2020-10-27 20:44 UTC, hartez commented
This is a good start, but it will only work if the visual state for Selected is set in resources; it doesn't quite work if the state is set directly in the data template. Working on an update to correct that.

2020-10-27 20:46 UTC, hartez commented
There, should work now even if the visual states are set in the template (see the changes to SingleBoundSelection.xaml to see what I mean).

2020-10-27 20:47 UTC, hartez approved these changes

2020-10-27 20:48 UTC, hartez commented
Starting up the automated UI test run now, once those pass and we can get a second review we'll get this merged.

2020-10-27 22:25 UTC, ronymesquita commented
Great!
:thumbsup:

2020-10-28 12:53 UTC, rmarinho requested changes
I think this needs rebase on top of 5.0. Also needs the correct formatting it's using spaces.

2020-10-28 14:02 UTC, developer9969 commented
@ronymesquita  @hartez  thank you for this fix , it will make a big difference to our apps as we use collection view all over the place and the selection item color was a big issue for our client

2020-10-28 21:02 UTC, hartez commented
> I think this needs rebase on top of 5.0. Also needs the correct formatting it's using spaces.

Why do you think it needs a rebase? No conflicts.

2020-10-28 22:55 UTC, closed without merging

2020-10-28 23:43 UTC, hartez commented
We ran into some merging issues with this PR, so we had to move it to a new one: https://github.com/xamarin/Xamarin.Forms/pull/12651.

Same commits, just a new branch.