Update LinearGradientBrush based on FlowDirection
xamarin/Xamarin.Forms pull request #11763
Opened 2020-08-12 15:41 UTC by jsuarezruiz

### Description of Change ###

Update LinearGradientBrush based on FlowDirection .

### Issues Resolved ### 

- fixes #11603 

### API Changes ###
 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

FlowDirection defines not only how text flows in a textual element but also the flow direction of almost every other UI element. With this changes, changing the FlowDirection also affects to a LinearGradientBrush.

### Before/After Screenshots ### 

![brush-flowdirection-ios](https://user-images.githubusercontent.com/6755973/90035861-9d5b6480-dcc2-11ea-9ac8-7df97d2c63c1.gif)

### Testing Procedure ###
Launch Core Gallery and navigate to the brushes gallery. Select the "" and apply FlowDirection changes to see the behavior.

### PR Checklist ###
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-08-24 21:20 UTC, samhouts requested changes
Can you make sure that any public signature changes are done with overloads instead of changing them?

Also, if we're changing API, please target 5.0.0.

Thanks!

2020-08-24 21:20 UTC, samhouts commented on Xamarin.Forms.Platform.Android/Renderers/CircularProgress.cs
> +		public void SetBackground(Color color, Brush brush, FlowDirection flowDirection)
breaking change

2020-09-07 09:00 UTC, jsuarezruiz commented
Retarget to 5.0.0.

2020-09-07 10:21 UTC, rmarinho commented
Build is failing @jsuarezruiz

2020-09-10 10:36 UTC, jsuarezruiz commented
@rmarinho Fixed the build error.

2020-09-10 11:39 UTC, rmarinho commented
need to resolve conflicts now @jsuarezruiz  :)

2020-09-18 21:37 UTC, samhouts commented
o no....more conflicts! 😱

2021-11-25 12:27 UTC, jfversluis commented
@jsuarezruiz there seems to be a lot of changes here. Should we skip this for Forms and move it to .NET MAUI?

2023-11-09 11:12 UTC, jfversluis commented
This is too big of a change to still add to Xamarin.Forms at this point in time. Thanks all for the time and effort here!

2023-11-09 11:12 UTC, closed without merging