[iOS] Automatically close the SwipeView if reset/reload the parent collection source
xamarin/Xamarin.Forms pull request #11813
Opened 2020-08-17 15:43 UTC by jsuarezruiz

### Description of Change ###

Automatically close the SwipeView if reset/reload the parent collection source.

### Issues Resolved ### 

- fixes #11808 

### API Changes ###

 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
![fix11808](https://user-images.githubusercontent.com/6755973/90415075-e17aaa80-e0b0-11ea-893f-664ab04c0726.gif)

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 11808.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-10-08 15:34 UTC, hartez approved these changes

2020-10-23 12:33 UTC, rmarinho requested changes
I think you need to hook to when the ItemsSource  on ListView our CollectionView changes so you can unsubscribe the `CollectionChanged`

2021-10-15 12:01 UTC, jsuarezruiz commented
/azp run

2023-02-21 08:15 UTC, jfversluis commented
Don't think this will happen for Xamarin.Forms anymore!

2023-02-21 08:15 UTC, closed without merging