[iOS] Fix Page orientation issue using LinearGradientBrush
xamarin/Xamarin.Forms pull request #11811
Opened 2020-08-17 15:33 UTC by jsuarezruiz

### Description of Change ###

 LinearGradientBrush fill the pages upon orientation change on iOS.

### Issues Resolved ### 

- fixes #11800 

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

![fix11800](https://user-images.githubusercontent.com/6755973/90413992-809ea280-e0af-11ea-9aff-74e3266aa2cc.gif)

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 11800. Rotate the emulator or device. If the gradient takes all the available space, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-10-29 18:12 UTC, hartez approved these changes

2020-10-29 20:28 UTC, rmarinho requested changes

2020-10-29 20:28 UTC, rmarinho commented on Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11800.cs
> +			Device.SetFlags(new List<string> { ExperimentalFlags.BrushExperimental });
Need to remove this

2020-10-30 08:38 UTC, jsuarezruiz commented on Xamarin.Forms.Controls.Issues/Xamarin.Forms.Controls.Issues.Shared/Issue11800.cs
> +			Device.SetFlags(new List<string> { ExperimentalFlags.BrushExperimental });
Removed.

2020-10-30 12:06 UTC, rmarinho approved these changes

2020-10-30 12:07 UTC, merged