[iOS] Fixed NRE in SearchBarRenderer OnSearchButtonClicked
xamarin/Xamarin.Forms pull request #11897
Opened 2020-08-24 10:15 UTC by jsuarezruiz

### Description of Change ###

Fixed NRE in SearchBarRenderer OnSearchButtonClicked on iOS.

### Issues Resolved ### 

- fixes #11865 

### API Changes ###

 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
![fix11865](https://user-images.githubusercontent.com/6755973/91033259-627ef800-e603-11ea-9c21-1cfae30b006c.gif)

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 11865. Type something in the SearchBar and tap the search button. If can navigate without any crash (disposed Control), the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-08-25 11:12 UTC, rmarinho requested changes

2020-08-25 11:12 UTC, rmarinho commented on Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
>  			Element.OnSearchButtonPressed();
```suggestion
			Elemen?t.OnSearchButtonPressed();
```

2020-08-25 11:12 UTC, rmarinho commented on Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
>  			Element.OnSearchButtonPressed();
Just in case

2020-08-25 11:12 UTC, rmarinho commented on Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
>  			Element.OnSearchButtonPressed();
```suggestion
			Element?.OnSearchButtonPressed();
```

2020-08-26 07:50 UTC, jsuarezruiz commented on Xamarin.Forms.Platform.iOS/Renderers/SearchBarRenderer.cs
>  			Element.OnSearchButtonPressed();
Applied the changes.

2020-08-26 10:37 UTC, rmarinho approved these changes

2020-08-26 10:37 UTC, merged