[WPF] Fix assembly version conflicts
xamarin/Xamarin.Forms pull request #11910
Opened 2020-08-24 23:43 UTC by krdmllr

### Description of Change ###

There are currently assembly version missmatches when working with the WPF .NET Core backend. 
The modifications to the assembly version information in this PR solve these issues when running the control gallery application. This is more of a workaround currently and I hope this could help in finding a longterm solution.
Some things I currently dont understand:
* Why is the control gallery explicitly asking for Version 2.0.0.0 of the WPF platform assembly. I could not find a reference to this version anywhere and a runtime error occures when I change the version to something else.
* In the Xamarin.Forms.Platform.WPF project we have to set `<GenerateAssemblyInfo>false</GenerateAssemblyInfo>`, otherwise the following compile error will show up: "The specified version string does not conform to the recommended format - major.minor.build.revision". When setting a version using the Version property, this error persists. In the control gallery, we can and have to set `<GenerateAssemblyInfo>true</GenerateAssemblyInfo>`.
* Why does this error occur in the control gallery? I created an empty wpf .net core and .net framework project, referenced the assemblies and could start up the code shown in https://github.com/xamarin/Xamarin.Forms/issues/10489 without modifications to the assembly infos.

### Issues Resolved ### 
*https://github.com/xamarin/Xamarin.Forms/issues/11328
*https://github.com/xamarin/Xamarin.Forms/issues/10489

### Platforms Affected ### 

- WPF

None

Not applicable

### Testing Procedure ###

* Clean bin folder of the Xamarin.Forms.Platform.WPF and Xamarin.Forms.ControlGallery.WPF project
* Build and run
* Application should show up.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-08-24 23:46 UTC, krdmllr commented
@PureWeen @jsuarezruiz @MagicAndre1981 fyi, you pinged me on this issue. I wont get around working further on this for the next week but perhaps it could help you to further investigate the issue. I suspect this has something to do with the WPF .NET Core tooling and how it creates assembly information, maybe someone from that team could help?

2020-08-25 09:29 UTC, rmarinho commented
/azp run

2020-08-25 12:06 UTC, jsuarezruiz commented
Tested and Core Gallery is working:

<img width="1923" alt="Captura de pantalla 2020-08-25 a las 14 03 05" src="https://user-images.githubusercontent.com/6755973/91171969-bc52f100-e6db-11ea-9f39-37d1da58b71e.png">

However, as Konrad said, this changes fix the issue with Core Gallery but we still need to know what is producing the assembly version missmatches.  Thanks for all the effort Konrad, I am not going to approve the PR for now (unless we want this PR now to fix Core Gallery and focus on fix the missmatche issue in another one). I will review the csproj of WPF Platform and Map projects.

2020-08-26 19:13 UTC, mattleibow commented
Might be related to this: https://github.com/dotnet/wpf/issues/1688

2020-08-26 19:22 UTC, mattleibow commented
The version number comes from here: https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Version.targets#L49

2020-08-26 19:27 UTC, mattleibow commented on Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("2.0.0.0")]
We shouldn't need both. The `GenerateAssemblyInfo` should automatically include this attribute. I get a compiler error with it...

2020-08-26 19:34 UTC, mattleibow commented
@jsuarezruiz  Did you test both netcore and netfx? My netfx still crashes, but netcore is fine...

2020-08-31 12:18 UTC, krdmllr commented
> @jsuarezruiz Did you test both netcore and netfx? ~My netfx still crashes, but netcore is fine...~
> 
> My netcoreapp crashes, but netfx is fine.

How does netcore crash? Did you clear bin/obj folders of the platform and galery project?

2020-09-01 19:59 UTC, krdmllr commented
> The version number comes from here:
> 
> https://github.com/xamarin/Xamarin.Forms/blob/719fc7a604ff0cce8922d717c99bfb0fa17e35e0/Version.targets#L49

So:
1. Why is the Assembly Version fixed?
2. When is this picked up and why is it not picked up when the wpl platform is build?
3. If the version is fixed, is it ok if we hardcode it in the platform project?

2020-09-01 20:10 UTC, PureWeen commented
@rmarinho  @samhouts ?

Do you know why Version.targets isn't being picked up on the WPF dll?

https://github.com/xamarin/Xamarin.Forms/pull/11910#issuecomment-685099324

2020-09-01 21:34 UTC, krdmllr commented
I digged deeper into the version file and think that the set version target has some order issue. I added some messages to understand what the $(Version) value is + disabled GenerateAssemblyVersion it works:
![image](https://user-images.githubusercontent.com/11095003/91908052-39b5cd00-ecab-11ea-9af8-e7087b836e6d.png)

I then changed the target order to verify that it should only run once after the git info target, which kinda worked but now the dll gets correctly generated!
![image](https://user-images.githubusercontent.com/11095003/91907805-cb710a80-ecaa-11ea-9bbd-f0a71204b31c.png)

The platform dll now has a usefull file version.
![image](https://user-images.githubusercontent.com/11095003/91908124-5baf4f80-ecab-11ea-9958-db42770358fe.png)

And the control gallery runs!

@rmarinho do you know how we could properly change the target order to make this work? I dont want to break other stuff where the beforetargets were required.

2020-09-01 21:43 UTC, rmarinho commented
I think this can work, can we keep the BeforeTargets too ?

2020-09-02 18:54 UTC, krdmllr commented
> I think this can work, can we keep the BeforeTargets too ?

I could only get it to work without BeforeTargets. Do we need them or could we maybe use other targets?

2020-09-03 11:33 UTC, rmarinho commented
@krdmllr can you take a look at #12011

2020-09-03 18:04 UTC, krdmllr commented
@rmarinho setting it like in your pr does not build for me

2020-09-04 11:22 UTC, rmarinho commented
Hi @krdmllr  so i asked @jsuarezruiz  to test my PR and he was able to run it.. 

Does it fail the same way for you? did you do a git  clean to the repo to make sure old dll is not around?

2020-09-06 16:01 UTC, krdmllr commented
@rmarinho @jsuarezruiz yes I cleared everything. Perhaps you did not enable the GenerateAssemblyInfo in the wpf project? We have to enable that but it also creates the error with the current versions file.

2020-09-07 09:46 UTC, rmarinho commented
@krdmllr i only pull the branch without any change.

2020-09-09 11:48 UTC, rmarinho commented
@krdmllr ok my solution also doesn't seem to be perfect. Doesn't sett the current version ok 

I tested this PR as is, and we generate a 2.0.0.0 fixed assembly and no file version

we can kind of fix it by adding still not the same as we have on targets:
```
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion(ThisAssembly.Git.BaseVersion.Major + "." 
			+ ThisAssembly.Git.BaseVersion.Minor + "." 
			+ ThisAssembly.Git.BaseVersion.Patch + "." 
			+ ThisAssembly.Git.Commits)]
[assembly: AssemblyInformationalVersion(ThisAssembly.Git.SemVer.Major + "."
			+ ThisAssembly.Git.SemVer.Minor + "."
			+ ThisAssembly.Git.SemVer.Patch
			+ ThisAssembly.Git.SemVer.DashLabel + "+"
			+ ThisAssembly.Git.Commits + "-sha."
			+ ThisAssembly.Git.Commit)]
```

Your solution for the targets file seems to not work for me it says theres a target cycle loop since AfterTargets and DependTargets are same

2020-09-10 10:22 UTC, rmarinho requested changes

2020-09-10 10:22 UTC, rmarinho commented on Xamarin.Forms.Platform.WPF/Properties/AssemblyInfo.cs
> +[assembly: AssemblyVersion("2.0.0.0")]
```suggestion
[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion(ThisAssembly.Git.BaseVersion.Major + "."
			+ ThisAssembly.Git.BaseVersion.Minor + "."
			+ ThisAssembly.Git.BaseVersion.Patch + "."
			+ ThisAssembly.Git.Commits)]
[assembly: AssemblyInformationalVersion(ThisAssembly.Git.SemVer.Major + "."
			+ ThisAssembly.Git.SemVer.Minor + "."
			+ ThisAssembly.Git.SemVer.Patch
			+ ThisAssembly.Git.SemVer.DashLabel + "+"
			+ ThisAssembly.Git.Commits + "-sha."
			+ ThisAssembly.Git.Commit)]
```

2020-09-10 10:25 UTC, rmarinho approved these changes
We are going with this solution for now, but will investigate how to fix to use the Version.targets

2020-09-10 10:43 UTC, merged