[Bug] [UWP] Correct the translation calculation of views
xamarin/Xamarin.Forms pull request #11933
Opened 2020-08-26 17:38 UTC by mattleibow

### Description of Change ###

When the translation offset for a view is calculated, it incorrectly uses the scale to multiply/divide the actual offset. Side bug, seems WPF does not scale at all.

This PR will correct the math, I hope.

### Issues Resolved ### 

- Fixes #11931

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-08-26 18:46 UTC, mattleibow commented
I may need help to see if this is actually UI testable... The scaling doesn't affect the bounds properties, so it is going to be a bit harder to check.

2020-08-26 19:49 UTC, mattleibow commented
BONUS: Fix the WPF rendering and also the iOS transform order... See screenshots :)

2020-08-26 20:02 UTC, mattleibow commented
I did not test Tizen and macOS yet.

2020-09-02 05:54 UTC, rookiejava commented
@mattleibow Tizen's result is here. I think it's OK.
![translation](https://user-images.githubusercontent.com/1029134/91936933-d0c26980-ed2b-11ea-8695-0318d97a67bb.gif)

2020-09-08 17:11 UTC, mattleibow commented
@rookiejava I think the rotation is distorting the text - see the before/after for iOS.

I think the order of scale and rotation are swapped...

2020-09-09 12:04 UTC, rookiejava commented
> I think the rotation is distorting the text - see the before/after for iOS.
> I think the order of scale and rotation are swapped...

@mattleibow gotcha! 

As you said, we need tp reverse the order of the two lines below. ( applyScale => applyRotation)

https://github.com/xamarin/Xamarin.Forms/blob/c5e8e31fa559c7632d2ff5209f199771e6d32ed1/Xamarin.Forms.Platform.Tizen/Renderers/VisualElementRenderer.cs#L1090-L1091

The result is as below.

**BEFORE** | **AFTER**
--- | --- 
<img src="https://user-images.githubusercontent.com/1029134/91936933-d0c26980-ed2b-11ea-8695-0318d97a67bb.gif" width=240 /> | <img src="https://user-images.githubusercontent.com/1029134/92595305-1f00db00-f2df-11ea-84c5-6686695e4b31.gif" width=240 /> 

Thanks! 😉

2020-09-10 06:51 UTC, mattleibow commented
Awesome! Could you crazy a quick or for that onto my branch, and then I'll merge when I wake up?

2020-09-14 00:50 UTC, rookiejava commented
> Awesome! Could you create a quick pr for that onto my branch, and then I'll merge when I wake up?

Done. Thanks!

2020-09-14 02:53 UTC, mattleibow commented
Merged! Thanks.

I think this PR is ready!!!

2020-11-10 19:38 UTC, PureWeen requested changes
@mattleibow is writing Unit Tests

2020-11-16 15:05 UTC, jsuarezruiz approved these changes

2020-11-16 15:05 UTC, jsuarezruiz commented on Xamarin.Forms.Platform.UAP.UnitTests/TransformationTests.cs
> +		public async Task TransformationConsistent(View view)
:heart:

2020-11-16 19:24 UTC, PureWeen requested changes
Looks like it still needs a little bit more rounding love @mattleibow 

![image](https://user-images.githubusercontent.com/5375137/99298277-15c84900-280f-11eb-811b-e9d0eec00e38.png)

2020-11-16 22:13 UTC, mattleibow commented
I am rounding to 3 decimal places... Maybe the library has a bug or something? Maybe it is the nfloat or something.

I'll check.

2020-11-17 12:26 UTC, mattleibow commented
I see lots more green, but still a bit of red...

2020-11-17 15:48 UTC, rmarinho commented
The iOS failure is not related.

2020-11-18 21:22 UTC, PureWeen approved these changes

2020-11-18 21:24 UTC, mattleibow commented
Another place were this actually shows up as what I think i an improvement is the "pinch gallery". Before, when you pinch, it would scale from the left edge. Afterwards, it scales from the center as expected.

2020-11-18 21:26 UTC, merged