[Core,iOS,Droid,UWP,Tizen] Remove MediaElement
xamarin/Xamarin.Forms pull request #12007
Opened 2020-09-02 18:54 UTC by rmarinho

### Description of Change ###

Remove MediaElement as it moves to XCT ,[ pr soon
](https://github.com/xamarin/XamarinCommunityToolkit/tree/mediaelement)

### Issues Resolved ### 

None

### API Changes ###

 Removed:
 - class MediaElement
 - class MediaElementRenderer

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP
- Tizen

### Behavioral/Visual Changes ###

Would need XCT to run Media

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-09-02 19:00 UTC, samhouts commented
I think MediaSource needs to go, too.

2020-09-03 07:04 UTC, rookiejava commented
I think below files need to go, too. (for Tizen)
- Xamarin.Forms.Platform.Tizen/Native/EmbeddingControls.cs
- Xamarin.Forms.Platform.Tizen/Native/LayoutCanvas.cs
- Xamarin.Forms.Platform.Tizen/Resource/img_button_pause.png
- Xamarin.Forms.Platform.Tizen/Resource/img_button_play.png

2020-09-08 13:15 UTC, StephaneDelcroix approved these changes

2020-09-09 16:16 UTC, jsuarezruiz requested changes
There are some pending lines to remove:
- In ControlGallery in UWP, Tizen and iOS. Example: https://github.com/xamarin/Xamarin.Forms/blob/remove-mediaelement/Xamarin.Forms.ControlGallery.WindowsUniversal/App.xaml.cs#L74
- From AssemblyInfo in Xamarin.Forms.Platform.Android.

2020-09-10 09:17 UTC, jsuarezruiz approved these changes

2020-09-10 09:22 UTC, merged