[UWP] Fix SwipeItem NRE no setting the Text
xamarin/Xamarin.Forms pull request #12087
Opened 2020-09-11 11:16 UTC by jsuarezruiz

### Description of Change ###

Fix SwipeItem NRE no setting the Text in UWP.

### Issues Resolved ### 

- fixes #12079 

### API Changes ###
 
 None

### Platforms Affected ### 

- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###
Launch Core Gallery and navigate to the Issue12079. Swipe to the right, if can open the SwipeView the test has passed.

### PR Checklist ###
- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-11-16 10:58 UTC, rmarinho approved these changes

2020-11-18 22:50 UTC, PureWeen requested changes
Looks good! Can you add a UI Test? Should be able to just make this one a platform unit test on UWP

2020-11-25 00:21 UTC, PureWeen requested changes
Test failing on UWP SwipeItemNoTextWindows

2020-12-03 19:19 UTC, jsuarezruiz commented
The test passed on Android/iOS but is failing on UWP.
<img width="1741" alt="Captura de pantalla 2020-12-03 a las 20 18 33" src="https://user-images.githubusercontent.com/6755973/101077169-be630080-35a4-11eb-8f88-31d2b48bc896.png">
The id is set on the control but Selenium can't find it, will take a look!

2020-12-14 19:53 UTC, PureWeen approved these changes

2020-12-14 21:17 UTC, merged