Fix WkWebViewRenderer to properly dispose and clear renderers
xamarin/Xamarin.Forms pull request #12163
Opened 2020-09-18 04:40 UTC by PureWeen

### Description of Change ###

- fixed WkWebViewRenderer to check for double dispose
- fixed WkWebViewRenderer to properly remove and dispose of associated renderers

### Issues Resolved ### 
- fixes #11962 

### Platforms Affected ### 
- iOS

### Testing Procedure ###
- ui tests pass

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-09-18 09:28 UTC, rmarinho requested changes
Build is failing, , think is with issue reproduction file.

2020-09-25 11:36 UTC, rmarinho approved these changes

2020-09-29 16:09 UTC, PureWeen commented
Here are the UI tests for this PR

https://dev.azure.com/xamarin/public/_releaseProgress?_a=release-pipeline-progress&releaseId=2338

2020-09-29 23:55 UTC, samhouts approved these changes

2020-09-29 23:56 UTC, merged