Make OnPlatform helpers public
xamarin/Xamarin.Forms pull request #12278
Opened 2020-09-27 21:56 UTC by pictos

### Description of Change ###

This PR changes the visibility of the ` PlatformConfigurationRegistry<TElement>` class to public decorated with the `EditorBrowsableState.Never` attribute. We need this into the XCT.

### Issues Resolved ### 

- Related to #12136

### API Changes ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-09-29 17:11 UTC, hartez requested changes

2020-09-29 17:11 UTC, hartez commented on Xamarin.Forms.Core/PlatformConfigurationRegistry.cs
> +	[EditorBrowsable(EditorBrowsableState.Never)]
You can leave off this attribute.

2020-09-29 23:06 UTC, pictos commented on Xamarin.Forms.Core/PlatformConfigurationRegistry.cs
> +	[EditorBrowsable(EditorBrowsableState.Never)]
done

2020-10-07 22:23 UTC, hartez approved these changes

2020-10-09 21:01 UTC, samhouts approved these changes

2020-10-09 21:01 UTC, merged