[iOS] Fix Page BackgroundColor issue using DarkTheme
xamarin/Xamarin.Forms pull request #12409
Opened 2020-10-08 10:45 UTC by jsuarezruiz

### Description of Change ###

Fix Page BackgroundColor issue using DarkTheme on iOS.

### Issues Resolved ### 

- fixes #12406 

### API Changes ###

 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 
![fix12406](https://user-images.githubusercontent.com/6755973/95448712-09c1af80-0964-11eb-9e07-3302d6542390.gif)

### Testing Procedure ###
Launch Core Gallery, then change the theme and verify that the page background color changed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2021-01-22 15:39 UTC, PureWeen requested changes
@jsuarezruiz it looks like this is happening on android also

https://github.com/xamarin/Xamarin.Forms/issues/13500

2021-02-03 04:18 UTC, PureWeen approved these changes

2021-02-03 20:02 UTC, hartez commented
iOS 12 failures are just the timeout problem, unrelated to this.

2021-02-04 16:35 UTC, Redth approved these changes

2021-02-04 16:40 UTC, merged