Added Shell parameters
xamarin/Xamarin.Forms pull request #12465
Opened 2020-10-13 01:39 UTC by pictos

### Description of Change ###

This PR adds support for users passes complex data in Shell navigation with the new object `ShellParameter`.

### Issues Resolved ### 

- fixes #6848

### API Changes ###

Added:
 - `class ShellParameter :  Dictionary <string, object>`
 - `static class ShellParameterExtensions`;

Changed:
 - `virtual void BaseShellItem.ApplyQueryAttributes(IDictionary<string, string> query)` => `virtual void BaseShellItem.ApplyQueryAttributes(ShellParameter query)`
 and all implementations
 
### Platforms Affected ### 

- Core/XAML (all platforms)

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

When you navigate with Shell you can pass `ShellParameter` in the method, just like:

`await Shell.Current.GoToAsync("//myAwesomeUri", new ShellParameter { {"My key", someObj} });`

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-10-13 01:45 UTC, pictos commented on Xamarin.Forms.Core/Shell/ShellParameter.cs
> +	public static class ShellParameterExtensions
I didn't find a good place to add this class. Can I create an extension folder?

2020-10-17 17:36 UTC, PureWeen requested changes

2020-10-17 17:36 UTC, PureWeen commented on Xamarin.Forms.Core/Shell/Shell.cs
> +		public Task GoToAsync(ShellNavigationState state, ShellParameter parameters = null)
Just adding optional parameters is a breaking change you have to add each overload manually

https://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/

2020-10-19 07:42 UTC, StephaneDelcroix commented
this removes the ability of serializing navigation Uris to strings (for, e.g., deep linking). I'd be more confortable if this was a Dictionary<string,string>

2020-10-19 07:44 UTC, StephaneDelcroix commented
> * This obsoletes the `IQueryAttributable` interface that no one uses because it's not documented anywhere

that's a lame excuse for obsoleting :)

2020-10-19 16:12 UTC, PureWeen commented
Apologies on this one @pictos 

I gave you premature guidance on this one and as it currently stands we can't really take in an API change like this pre .NET MAUI

2020-12-01 07:39 UTC, PureWeen commented
/azp run

2020-12-01 07:50 UTC, PureWeen commented
/azp run

2020-12-11 12:49 UTC, PureWeen commented
/azp run

2020-12-29 13:43 UTC, PureWeen commented
@pictos can you fix the conflicts?

2020-12-29 22:57 UTC, pictos commented
Yes, is it ok to solve it by tomorrow?

2020-12-30 00:59 UTC, pictos commented on Xamarin.Forms.Core/Shell/Shell.cs
> +		internal Task GoToAsync(ShellNavigationState state, ShellRouteParameters parameters)
@PureWeen not sure if we still need those methods here...

2021-01-07 23:36 UTC, PureWeen commented
Re-closing this one again unfortunately :-/ 

I've been chatting with @pictos  a bit of how to bring this behavior to XCT

2021-01-07 23:36 UTC, closed without merging

2021-02-01 09:07 UTC, angelru commented
will it be available in XCT?