Renderer to Handler and Handler to Renderer Shims
xamarin/Xamarin.Forms pull request #12546
Opened 2020-10-20 21:40 UTC by PureWeen

### Description of Change ###

- Wire up our Registrar so that everything registered via assembly scanning can be auto auto shimmed or use a handler
- Create `HandlerToRendererShim` for cases where people are still in the Context of a Forms app and will call Platform.CreateRenderer
- Create `RendererToHandlerShim` for cases where the user has registered a renderer that only implements IVisualElementRenderer

### API Changes ###

```C#
public class RendererToHandlerShim : Xamarin.Platform.IViewHandler, IAndroidViewHandler
```

```C#
public class HandlerToRendererShim : IVisualElementRenderer
```

### Platforms Affected ### 
- iOS
- Android

### Examples ###

#### Legacy Apps
Given the following code 
```C#
			SetMainPage(new ContentPage()
			{
				Content = new StackLayout()
				{
					Children = {
						new Button()
					}
				}
			});
```

Button can be registered to either a Handler or a Renderer and the registrar will react accordingly. The ContentPage calls CreateRenderer on its content which will return an IVisualElementRenderer. If the Content is of type IViewHandler then it gets wrapped with a HandlerToRendererShim so that ContentPage can still render the control successfully

#### Future Apps

If you just register a Shim against the handler then the Shim will reach out to the old registrar for the type

```C#
			Xamarin.Forms.Internals.Registrar.Registered.Register(typeof(Xamarin.Forms.Button), typeof(Xamarin.Forms.Platform.Android.FastRenderers.ButtonRenderer));
			RegistrarHandlers.Handlers.Register<Xamarin.Forms.Button>((type) =>
			{
				RendererToHandlerShim rendererToHandlerShim = new RendererToHandlerShim();
				return rendererToHandlerShim;
			});
```

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-10-22 00:10 UTC, PureWeen commented on src/Forms/src/Xamarin.Forms.Core/View.cs
> -		#region IView
@hartez is it alright that I moved these to VisualElement?

2020-10-22 00:53 UTC, PureWeen commented
/azp run

2020-10-23 10:52 UTC, gitKRM commented
don't  subscribe, I'm getting over 100 emails a day from this subscription

2020-12-02 08:53 UTC, jsuarezruiz requested changes
@PureWeen Could we add some tests to validate the use of `RendererToHandlerShim` and `RendererToHandlerShim`?

2021-01-08 11:13 UTC, rmarinho commented
@PureWeen can e rebase and add some tests to make this works fine?

2021-01-14 21:30 UTC, PureWeen commented
@rmarinho @jsuarezruiz 

So in theory our Control Gallery tests are the UI Tests for the shims.
You Shim a Handler into the Control.Gallery and then all the Control Gallery tests pass. 

Also, we can't really do any tests for RendererToHandlerShim until we have the Handler.Testing project setup or the Appium project

At that point we can write some tests to verify that the renderers shim correctly into handlers.

2021-01-21 14:18 UTC, merged