fix-9992 - Android - CollectionView - VerticalItemSpacing and HorizontalItemSpacing was not set for the new added item
xamarin/Xamarin.Forms pull request #12596
Opened 2020-10-25 14:37 UTC by BrayanKhosravian

### Description of Change ###
fix-9992 - Android - CollectionView - VerticalItemSpacing and HorizontalItemSpacing was not set for the new added item

### Issues Resolved ### 

- fixes #9992

### API Changes ###
 None

### Platforms Affected ### 
- Android

### Behavioral/Visual Changes ###
Android - CollectionView - VerticalItemSpacing and HorizontalItemSpacing was not set for the new added item

### Before/After Screenshots ### 

### Broken
![vertical_broken](https://user-images.githubusercontent.com/35541212/97110076-7adcc300-16d7-11eb-91b0-e33166ee8fd3.gif)

![horizontal_broken](https://user-images.githubusercontent.com/35541212/97110085-8203d100-16d7-11eb-9d86-476abee19057.gif)

### Fixed
![vertical_fixed](https://user-images.githubusercontent.com/35541212/97110104-a2339000-16d7-11eb-9bc9-979ffedd3f39.gif)

![Uploading horizontal_fixed.gif…]()

Not applicable

### Testing Procedure ###
Just add a new item to the `CollectionView` and check if the item spacing is applied

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-10-25 14:56 UTC, BrayanKhosravian reviewed
How should this be tested?

2020-10-25 14:56 UTC, BrayanKhosravian commented on Xamarin.Forms.Platform.Android/CollectionView/SpacingItemDecoration.cs
>  				if (parent.GetChildAdapterPosition(view) != parent.GetAdapter().ItemCount - 1)
I don't understand why this exists. `if (parent.GetChildAdapterPosition(view) != parent.GetAdapter().ItemCount - 1)`

2020-10-25 14:56 UTC, BrayanKhosravian commented on Xamarin.Forms.Platform.Android/CollectionView/SpacingItemDecoration.cs
>  				if (parent.GetChildAdapterPosition(view) != parent.GetAdapter().ItemCount - 1)
Same for this one. "I don't understand why this exists." `if (parent.GetChildAdapterPosition(view) != parent.GetAdapter().ItemCount - 1)`

2020-11-16 21:51 UTC, BrayanKhosravian commented
I think it would have been better for the history to do a rebase.

2020-12-02 11:36 UTC, jsuarezruiz requested changes
Could you rebase to fix the current conflict?. Thanks!.

2020-12-02 11:41 UTC, BrayanKhosravian commented
@jsuarezruiz Should I rebase onto 5.0.0 or another branch?

2021-12-24 14:33 UTC, jfversluis commented
Hey @BrayanKhosravian thank you so much for your time and efforts on this. I am so sorry we kept this around for so long. I have checked and it seems this got fixed in the meantime with another PR already. Despite everything I hope you'll join us with .NET MAUI where we're improving all kinds of things, including the process for PRs (from the community).

Closing this one for now, let me know if you still thing something is wrong in this area. Thanks!

2021-12-24 14:33 UTC, closed without merging