Remove unnecessary UpdateConstraints calls when rotating
xamarin/Xamarin.Forms pull request #12728
Opened 2020-11-03 22:07 UTC by hartez

### Description of Change ###

Removes unnecessary constraints update calls during InvalidateLayout which were causing auto-layout errors for CarouselView (and making HTML Labels occasionally disappear). 

Also removes some unecessary overrides from CarouselView Layout/Controller (deferring to ItemsView Layout/Controller). 

### Issues Resolved ### 

- fixes #12193

### API Changes ###
 
None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Automated test

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-11-05 17:52 UTC, rmarinho commented
Seems a iOS test is failing  CarouselViewPositionFromVisibilityChangeTest_apple_iphone_x_11_4_1

2020-11-05 17:53 UTC, rmarinho requested changes
Seems a iOS test is failing CarouselViewPositionFromVisibilityChangeTest_apple_iphone_x_11_4_1

2020-11-08 12:11 UTC, rmarinho commented
failing tests ios12/ios11 -- not sure why on CI reports 51 and here just 18 and 1 :/

2020-11-11 17:51 UTC, rmarinho approved these changes

2020-11-11 17:59 UTC, jsuarezruiz approved these changes

2020-11-11 18:02 UTC, merged