Remove markup extensions
xamarin/Xamarin.Forms pull request #12730
Opened 2020-11-03 23:28 UTC by PureWeen

### Description of Change ###

Markup extensions are being moved to the Xamarin Community Toolkit

### API Changes ###
- Removed all the APIS from the Xamarin.Forms.Markup namespace

### Platforms Affected ### 
- Core/XAML (all platforms)

### Behavioral/Visual Changes ###
- User will have to install the Xamarin Community Toolkit if they want to use Markup Extensions

### Testing Procedure ###
- UI Tests are all passing

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-11-04 08:05 UTC, jsuarezruiz requested changes
Almost everything is removed, we need to also remove the `MarkupExperimental` flag (used in a couple of issues).

2020-11-04 16:46 UTC, PureWeen commented
UITESTS are here

https://dev.azure.com/xamarin/public/_releaseProgress?_a=release-pipeline-progress&releaseId=2454

2020-11-06 08:26 UTC, jsuarezruiz approved these changes

2020-11-06 08:27 UTC, jsuarezruiz commented
Moved to the Xamarin Community Toolkit: https://github.com/xamarin/XamarinCommunityToolkit/pull/522

2020-11-06 11:15 UTC, rmarinho approved these changes

2020-11-06 11:15 UTC, merged