[Android] SwipeView used in a CollectionView fires the SelectionChangedCommand unintentionally
xamarin/Xamarin.Forms pull request #12736
Opened 2020-11-04 13:48 UTC by jsuarezruiz

### Description of Change ###

Avoid fire the CollectionView SelectionChangedCommand event if the user tap a Button for example. With the change from this PR, the behavior is the same the behavior as without using SwipeView.

### Issues Resolved ### 

- fixes #11982

### API Changes ###
 
 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

#### Before
![issue11982](https://user-images.githubusercontent.com/6755973/98119044-5d181680-1eac-11eb-85e1-6643f7126b96.gif)

#### After
![fix11982](https://user-images.githubusercontent.com/6755973/98119331-c39d3480-1eac-11eb-9ee4-1174f9a16dbb.gif)

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 11982. In the CollectionView using the SwipeView, tap the Button. If not trigger the SelectionChanged, the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-11-11 12:22 UTC, jsuarezruiz commented
Added changes to fix the build error.

2020-12-03 22:05 UTC, rachelkang commented
Perhaps not within the scope of this PR, but what's the expected behavior on iOS? I'm seeing that it's different on iOS than on Android

Also, what's the expected behavior when clicking on the "Command" button itself? I sometimes get the dialog and I sometimes see the "-PRESSED" added on

2020-12-16 23:34 UTC, rmarinho commented
@jsuarezruiz  build is failing

2020-12-18 10:57 UTC, rmarinho commented
@jsuarezruiz  can we UITest this?

2020-12-18 17:51 UTC, jsuarezruiz commented
Sure
![Uploading Captura de pantalla 2020-12-18 a las 18.49.03.png…]()

2020-12-18 18:03 UTC, jsuarezruiz commented
@rachelkang Could you try again? The behavior should be the same on Android and iOS.

2020-12-18 19:13 UTC, rachelkang reviewed
No longer seeing the different behaviors described in last comment

2020-12-18 19:13 UTC, rachelkang commented on Xamarin.Forms.Platform.Android/Renderers/SwipeViewRenderer.cs
> +
Why did you move this code up?

2020-12-28 14:02 UTC, rmarinho requested changes
Build is failing 

```
D:\agent\1\s\Xamarin.Forms.Controls\Xamarin.Forms.Controls.csproj" (GetTargetFrameworks target) (9:21) ->
  D:\agent\1\s\Xamarin.Forms.Controls\Xamarin.Forms.Controls.csproj(160,3): error MSB4024: The imported project file "D:\agent\1\s\Xamarin.Forms.Controls.Issues\Xamarin.Forms.Controls.Issues.Shared\Xamarin.Forms.Controls.Issues.Shared.projitems" could not be loaded. The 'EmbeddedResource' start tag on line 2026 position 6 does not match the end tag of 'ItemGroup'. Line 2078, position 5.
```

2023-11-29 19:55 UTC, jfversluis commented
Not sure if this fix is still correct and seeing where we are in the Xamarin lifecycle, we probably won't be merging this anymore

2023-11-29 19:55 UTC, closed without merging