[iOS] Remove hardcoded value on CarouselView loop calculations
xamarin/Xamarin.Forms pull request #12787
Opened 2020-11-09 17:31 UTC by rmarinho

### Description of Change ###

Don't use hardcoded number to fix calculations to recenter the CarouselView and fake the loop feature when the collection just has a couple of items.

### Issues Resolved ### 

- fixes #12754 

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

Should not crash.

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Added uitkst for issue 12574, make sure you can scroll the items.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-11-11 10:03 UTC, jsuarezruiz commented
Failing UITests seem unrelated (not CarouselView tests).

2020-11-11 12:14 UTC, rmarinho commented
failing tests are not related.

2020-11-12 15:08 UTC, jsuarezruiz requested changes
Is working fine, and the changes have sense but, can we modify the sample to remove/add item/s. Just to be sure the loop calculations are correct changing the items count.

2020-11-12 17:41 UTC, jsuarezruiz approved these changes

2020-11-12 17:49 UTC, hartez approved these changes

2020-11-12 17:53 UTC, merged