[iOS] Fix pushing same page as a modal on iOS13
xamarin/Xamarin.Forms pull request #12871
Opened 2020-11-16 17:55 UTC by rmarinho

### Description of Change ###

There's a issue on iOS13  that pushing a modal using your app side by side with other app it causes issues rendering the second time. 
The particular issue is also related with retaining the pushed page , it keeps it's bounds, and we need to force the relayout.
Workaround could be to just reset is bounds when is popped.

### Issues Resolved ### 

- fixes #8988

### API Changes ###
 
 None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

### Testing Procedure ###

Go to Issue8988 , click Next, check the page loaded, click Go Back, then click again Next and make sure the page loads fine.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-11-16 18:56 UTC, rmarinho commented on Xamarin.Forms.Platform.iOS/ModalWrapper.cs
> -			if (Forms.IsiOS13OrNewer)
this was duplicated

2020-11-16 18:56 UTC, rmarinho commented on Xamarin.Forms.Platform.iOS/DisposeHelpers.cs
> +					visualElement.Layout(new Rectangle(0, 0, -1, -1));
The fix is here.

2020-11-17 15:52 UTC, jsuarezruiz approved these changes

2020-11-20 03:19 UTC, PureWeen requested changes
@rmarinho curious your thoughts on this approach.

https://github.com/xamarin/Xamarin.Forms/compare/fix-8988-shane

2020-11-20 15:40 UTC, rmarinho commented
@PureWeen  just tested, and yeah looks a better fix

2020-11-24 04:24 UTC, PureWeen approved these changes

2020-11-24 16:29 UTC, jsuarezruiz approved these changes

2020-11-24 17:17 UTC, merged