[X] deprecate FontImageExtension
xamarin/Xamarin.Forms pull request #12903
Opened 2020-11-19 09:44 UTC by StephaneDelcroix

### Description of Change ###

this markup extension is a pass-through and does nothing, but add some
restricition (can't bind, or set dynamic resource to Color, e.g.). Using
the FontImageSource as a markup, like in `{FontImageSource}`, doesn't
have those restricitions, and reduce the amount of processing and
allocation. It should be used instead

### Issues Resolved ### 

- fixes #12851

### API Changes ###

 
 None

### Platforms Affected ### 

- Core/XAML (all platforms)
- iOS
- Android
- UWP

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-11-19 12:37 UTC, jsuarezruiz commented
There is a compilation error:
`obj\Release\Design\Xamarin.Forms.Xaml.AttributeTableBuilder.cs(45,19): error CS0618: 'FontImageExtension' is obsolete: 'This markup extension is deprecated. Use "{FontImageSource}" syntax.' [D:\agent\1\s\Xamarin.Forms.Xaml.Design\Xamarin.Forms.Xaml.Design.csproj]`

2020-11-19 12:39 UTC, jsuarezruiz requested changes
Looks good but there is a compilation error:
`obj\Release\Design\Xamarin.Forms.Xaml.AttributeTableBuilder.cs(45,19): error CS0618: 'FontImageExtension' is obsolete: 'This markup extension is deprecated. Use "{FontImageSource}" syntax.' [D:\agent\1\s\Xamarin.Forms.Xaml.Design\Xamarin.Forms.Xaml.Design.csproj]`

2020-11-19 13:20 UTC, StephaneDelcroix commented
@jsuarezruiz I know, I'm working on releasing a version of XF.Design that fixes it

2021-09-17 07:48 UTC, jsuarezruiz commented
/azp run

2021-11-18 12:45 UTC, jfversluis commented
Let's not do this anymore for Forms, marked for .NET MAUI

2021-11-18 12:45 UTC, closed without merging