[macOS] Hang App scaling a View to zero
xamarin/Xamarin.Forms pull request #13005
Opened 2020-11-30 15:20 UTC by jsuarezruiz

### Description of Change ###

Hang or crash macOS App scaling a View to zero.

### Issues Resolved ### 

- fixes #8981

### API Changes ###
 
 None

### Platforms Affected ### 

- macOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

#### Before
Hang in the first case and getting a crash in the second case setting the Scale to zero.

#### Ater
![fix8981](https://user-images.githubusercontent.com/6755973/100627609-7daa8380-3327-11eb-808f-dd7badcd90ab.gif)
![macos-scale-issue](https://user-images.githubusercontent.com/6755973/100627594-797e6600-3327-11eb-99ca-33ca1f43af64.gif)

### Testing Procedure ###

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-12-10 21:15 UTC, mattleibow requested changes
Scaling to negative values on both X and Y cause the last axis to actually snap to 0.

I think this is because we only update the fields when at least one of the axis are positive. However, when both are negative, the logic fails.

Also, since the variables in the scope have the same name, it might cause a bit of confusion.

![scale](https://user-images.githubusercontent.com/1096616/101830391-1a95c980-3b3d-11eb-9306-2a6954160aaf.gif)

2021-01-19 12:28 UTC, jsuarezruiz commented
@mattleibow Thanks for the feedback!. I have made changes to cover all cases.
![fix8981](https://user-images.githubusercontent.com/6755973/105034695-2046cf00-5a5a-11eb-9a61-822aba915692.gif)

2021-02-16 14:09 UTC, mattleibow approved these changes

2021-02-16 14:09 UTC, mattleibow commented
/azp run

2021-05-21 07:26 UTC, merged