Enable ScrollTo tests for Android, UWP; implement ScrollTo with group index for Android
xamarin/Xamarin.Forms pull request #13007
Opened 2020-11-30 22:40 UTC by hartez

### Description of Change ###

Activating the ScrollTo automated tests for Android/UWP (they were only set to run for iOS).

Implemented ScrollTo with group index/item index for Android.

### API Changes ###

public interface IGroupedItemsPosition
{
	int GetPosition(int groupIndex, int itemIndex);
}

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Tests were already there, just turning them on and making them pass on Android.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2021-06-29 14:19 UTC, rmarinho approved these changes

2021-07-01 17:41 UTC, rmarinho requested changes
@hartez  it's failing some tests on UWP, can take a look ? seems to work fine if i try it manually 

https://dev.azure.com/xamarin/public/_releaseProgress?releaseId=2932&_a=release-environment-extension&environmentId=143428&extensionId=ms.vss-test-web.test-result-in-release-environment-editor-tab

![image](https://user-images.githubusercontent.com/1235097/124166503-d2b79f00-da9a-11eb-91ee-2c7283cb6e91.png)

2021-07-07 08:56 UTC, jsuarezruiz approved these changes

2021-07-12 09:08 UTC, rmarinho approved these changes

2021-07-12 09:08 UTC, merged