Restore ability to display header, footer, and empty view simultaneously
xamarin/Xamarin.Forms pull request #13247
Opened 2020-12-29 05:41 UTC by hartez

### Description of Change ###

Somewhere along the way the CollectionView's EmptyView on iOS regressed and no longer could display the header, footer, and EmptyView at the same time (the EmptyView would sit on top of the header, obscuring it).

These changes undo the changes which caused the regression and fix the problem a different way, leaving the EmptyView and Header intact.

### Issues Resolved ### 

- fixes #8326 (again)

### API Changes ###

None

### Platforms Affected ### 

- iOS

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

Not applicable

### Testing Procedure ###

Control Gallery -> Issue 8326; the header, footer, and empty view should all be visible when the test loads.
Control Gallery -> CollectionView Gallery -> EmptyView Gallery -> EmptyView RTL; the empty view text should only shift alignment when the page is set to RTL, rather than horizontally flipping the text (see #12892).

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-12-29 21:50 UTC, PureWeen requested changes
1)  If you set the drop down to RTL before triggering the Empty View then the text is flipped
- Open Empty View RTL Gallery
- Set Drop down to RTL
- Enter in a filter that causes empty view to show
- Text is flipped horizontally

![image](https://user-images.githubusercontent.com/5375137/103316304-b2286280-49ed-11eb-848f-f2eee65350cc.png)


2) The footer view renderers differently on iOS vs Android (should this be logged into a different issue?)

![image](https://user-images.githubusercontent.com/5375137/103316252-8ad19580-49ed-11eb-99d6-8a649dcec1ad.png)

2020-12-30 21:24 UTC, PureWeen approved these changes

2020-12-31 00:06 UTC, hartez commented
iOS 13 test failure is not related to these changes.

2020-12-31 14:04 UTC, rmarinho approved these changes

2020-12-31 14:05 UTC, merged