[Android] Fix crash scrolling ListView using a CarouselView in template
xamarin/Xamarin.Forms pull request #13452
Opened 2021-01-19 09:17 UTC by jsuarezruiz

### Description of Change ###

Fix crash scrolling ListView using a CarouselView in template on Android.

### Issues Resolved ### 

- fixes #13441 

### API Changes ###

 None

### Platforms Affected ### 

- Android

### Behavioral/Visual Changes ###

None

### Before/After Screenshots ### 

![fix13441](https://user-images.githubusercontent.com/6755973/105013309-68a4c380-5a3f-11eb-90e6-a70b892649f5.gif)

### Testing Procedure ###
Launch Core Gallery and navigate to the issue 13441. Scroll to the end, without exceptions the test has passed.

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2021-01-26 16:55 UTC, rmarinho approved these changes

2021-02-03 12:18 UTC, rmarinho requested changes
@jsuarezruiz  is failing 1 test

2021-03-04 10:03 UTC, jsuarezruiz commented
/azp run

2023-11-29 19:59 UTC, jfversluis commented
Not sure if this fix is still correct and seeing where we are in the Xamarin lifecycle, we probably won't be merging this anymore

2023-11-29 19:59 UTC, closed without merging