Fix infinite slider width issue
xamarin/Xamarin.Forms pull request #13846
Opened 2021-02-24 02:34 UTC by hartez

### Description of Change ###

Fix issue with UISlider (and possibly other controls) misbehaving when calling SizeThatFits with infinite width.

If the control tries to claim infinite width or height, call SizeToFit and return the frame instead. (This is basically the same fix Forms has for SliderRenderer).

### Issues Resolved ### 

- (hopefully) fixes broken 7361 test in CG

### API Changes ###
 
None

### Platforms Affected ### 

- iOS

### Testing Procedure ###

Automated device test

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2021-02-24 22:29 UTC, PureWeen requested changes
Should we also change this to call GetDesiredSize on the Android side?

https://github.com/xamarin/Xamarin.Forms/blob/5c6e540b0573258b1bb6f2eae546ffdf1d5d5536/src/Platform.Renderers/src/Xamarin.Forms.Platform.Android/HandlerToRendererShim.cs#L41

2021-02-25 17:56 UTC, hartez commented
> Should we also change this to call GetDesiredSize on the Android side?
> 
> https://github.com/xamarin/Xamarin.Forms/blob/5c6e540b0573258b1bb6f2eae546ffdf1d5d5536/src/Platform.Renderers/src/Xamarin.Forms.Platform.Android/HandlerToRendererShim.cs#L41

Good call. Done.

2021-02-25 18:05 UTC, mattleibow approved these changes
Can't comment on how everything fits together as I am still grasping all the internals, but the code looks sound.

2021-02-25 19:10 UTC, jsuarezruiz approved these changes

2021-02-25 21:42 UTC, merged