Androidx material bump
xamarin/Xamarin.Forms pull request #9701
Opened 2020-02-24 23:04 UTC by PureWeen

### Description of Change ###

Update Xamarin.Google.Android.Material 1.1.0-rc2 

### Platforms Affected ### 
- Android

### Behavioral/Visual Changes ###
In theory there shouldn't be any. Compare the Visual Gallery on the previous version to this one

### Testing Procedure ###
- open visual gallery, compare to ios, and compare to previous version

### PR Checklist ###

- [ ] Targets the correct branch
- [ ] Tests are passing (or failures are unrelated)

2020-04-09 15:36 UTC, PureWeen commented
Currently blocked by
https://github.com/xamarin/AndroidX/issues/76

2020-09-09 15:29 UTC, hartez requested changes

2020-09-09 15:29 UTC, hartez commented on Xamarin.Forms.Material.Android/MaterialFormsTextInputLayoutBase.cs
> +				//EditText.SetHintTextColor(global::Android.Graphics.Color.Transparent);
Is this commenting-out intentional?

2020-12-11 17:05 UTC, PureWeen commented
@rmarinho I tested the nugets on this one and it pulls in the right nuget versions

```
 "Xamarin.AndroidX.Annotation/1.1.0.7": {
        "type": "package",
        "dependencies": {
          "Xamarin.AndroidX.Migration": "1.0.8"
        },
```

2020-12-16 11:32 UTC, jsuarezruiz requested changes
I have found some differences with the change. For example (left updated version, right 5.0.0 branch).

2020-12-16 15:05 UTC, rmarinho approved these changes

2020-12-16 22:38 UTC, merged